---
version: "3"

services:
  pulp-galaxy:
    image: "galaxy-dev/pulp-galaxy:latest"
    build:
      context: "."
      dockerfile: "docker/pulp_galaxy/Dockerfile"
    command: ['run', 'pulp-galaxy']
    ports:
      - "5001:8000"
    depends_on:
      - postgres
      - redis

  pulp-resource-manager:
    image: "galaxy-dev/pulp-galaxy:latest"
    depends_on:
      - postgres
      - redis

  pulp-worker:
    image: "galaxy-dev/pulp-galaxy:latest"
    depends_on:
      - postgres
      - redis

  pulp-content-app:
    image: "galaxy-dev/pulp-galaxy:latest"
    depends_on:
      - postgres
      - redis

  postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  redis:
    image: "redis:5"
    volumes:
      - "redis_data:/data"


volumes:
  pg_data: {}
  pulp_data: {}
  redis_data: {}
